'''
Created on 15/09/2013

Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

http://projecteuler.net/problem=2

@author: Antek
'''

def update_values(prev, prev_prev):
    return(prev + prev_prev, prev)


def fib(maxval):
    num = 0
    prev = 1
    prev_prev = 0
    while num < maxval:
        yield num
        num = prev + prev_prev
        prev, prev_prev = update_values(prev, prev_prev)

if __name__ == '__main__':
    print reduce(lambda x, y: x + y, [x for x in fib(4000000) if x % 2 == 1])