'''
Created on 15/09/2013

Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

http://projecteuler.net/problem=2

@author: Antek
'''

def fib():
    num = 0
    prev = 1
    prev_prev = 0
    current = 0
    while current <= 4000000:
        print num
        if num < 2:
            yield num
        else:
            current = prev + prev_prev
            prev_prev = prev
            prev = current
            while current % 2 == 1:
                current = prev + prev_prev
                prev_prev = prev
                prev = current
                num += 1
            yield current
        num += 1

if __name__ == '__main__':
    print [x for x in fib()]